import { ExpenseRequest, UserProfile, EnterpriseAuditLog, JournalEntry, DepartmentBudget, Department } from '../types';
import JSZip from 'jszip';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

type BackupData = {
  requests: ExpenseRequest[];
  users: UserProfile[];
  departments: Department[];
  auditLogs: EnterpriseAuditLog[];
  journalEntries: JournalEntry[];
  budgets: DepartmentBudget[];
};

export async function exportCompleteERPBackupToJSON(data: BackupData, reporterName: string) {
  const jsonStr = JSON.stringify(data, null, 2);
  const blob = new Blob([jsonStr], { type: 'application/json' });
  downloadBlob(blob, `ERP_Master_Backup_${formatDate()}.json`);
}

export async function exportCompleteERPBackupToCSV(data: BackupData, reporterName: string) {
  // Simple CSV of just requests for demonstration
  const headers = ['ID', 'Title', 'Date', 'Amount', 'Status', 'Employee', 'Department'];
  const rows = data.requests.map(r => [
    r.id,
    `"${r.title.replace(/"/g, '""')}"`,
    r.date,
    r.amount,
    r.status,
    `"${r.employeeName}"`,
    `"${r.department}"`
  ]);
  const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });
  downloadBlob(blob, `ERP_Master_Backup_${formatDate()}.csv`);
}

export async function exportCompleteERPBackupToPDF(data: BackupData, reporterName: string) {
  const doc = new jsPDF();
  doc.setFontSize(16);
  doc.text('ERP Master Backup Report', 14, 20);
  doc.setFontSize(10);
  doc.text(`Generated by: ${reporterName}`, 14, 30);
  doc.text(`Date: ${new Date().toLocaleString()}`, 14, 36);

  // AutoTable for Requests
  const head = [['ID', 'Title', 'Date', 'Amount', 'Status']];
  const body = data.requests.map(r => [
    r.id,
    r.title,
    r.date,
    r.amount.toString(),
    r.status
  ]);

  (doc as any).autoTable({
    startY: 45,
    head: head,
    body: body,
    theme: 'grid',
    styles: { fontSize: 8 },
    headStyles: { fillColor: [41, 128, 185] }
  });

  doc.save(`ERP_Master_Backup_${formatDate()}.pdf`);
}

export async function exportCompleteERPBackupToZIP(data: BackupData, reporterName: string) {
  const zip = new JSZip();
  
  // JSON
  zip.file(`backup_${formatDate()}.json`, JSON.stringify(data, null, 2));

  // CSV (Requests)
  const headers = ['ID', 'Title', 'Date', 'Amount', 'Status', 'Employee', 'Department'];
  const rows = data.requests.map(r => [
    r.id,
    `"${r.title.replace(/"/g, '""')}"`,
    r.date,
    r.amount,
    r.status,
    `"${r.employeeName}"`,
    `"${r.department}"`
  ]);
  const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  zip.file(`requests_${formatDate()}.csv`, '\uFEFF' + csvContent);

  // We could add the Excel file here, but it requires returning buffer from ExcelJS.
  // For simplicity, we just zip JSON and CSV
  
  const blob = await zip.generateAsync({ type: 'blob' });
  downloadBlob(blob, `ERP_Master_Backup_${formatDate()}.zip`);
}

function formatDate() {
  const d = new Date();
  return `${d.getFullYear()}${(d.getMonth()+1).toString().padStart(2,'0')}${d.getDate().toString().padStart(2,'0')}_${d.getHours().toString().padStart(2,'0')}${d.getMinutes().toString().padStart(2,'0')}`;
}

function downloadBlob(blob: Blob, filename: string) {
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
